[supervisord]
nodaemon=true
user=root

[program:backend]
directory=/app/backend
command=uvicorn app.main:app --host 127.0.0.1 --port 8000
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:ai-rag]
directory=/app/ai-rag
command=uvicorn app.main:app --host 127.0.0.1 --port 8001
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=nginx -g "daemon off;"
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0